# Start Alacritty Themes
import = ["/Users/andrew/.config/alacritty/colors/base16-rose-pine-moon.toml"]
# End Alacritty Themes

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
blur = true
dimensions = { lines = 30, columns = 120 }
# opacity = 0.98
# padding = { x = 10, y = 10 }

[font]
size = 17
# offset = { y = 10 }
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }
bold.style = "Regular"
italic.style = "Regular"


[keyboard]
bindings = [
  { key = "n", mods = "Control | Shift", action = "CreateNewWindow" },
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
]


[colors.primary]
# background = "#0A0A12"
# background = "#1a1c26"
