# Start Alacritty Themes
import = [
  "C:\\Users\\Andrew\\AppData\\Roaming\\alacritty\\colors\\base16-tokyo-night-terminal-dark.toml",
]
# End Alacritty Themes

shell = "wsl -d Ubuntu-22.04 --cd ~ tmux"
# shell = "pwsh -nologo -wd ~"

[window]
decorations = "none"
opacity = 0.99

[window.padding]
x = 20
y = 20

[window.dimensions]
lines = 35
columns = 110

[font]
size = 13.2
offset = { y = 6 }
bold = { style = "Regular" }

[font.normal]
family = "Hack Nerd Font"

[cursor.style]
shape = "Block"
blinking = "Always"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  # {key,mods,mode,action|chars}
  { key = "n", mods = "Control | Shift", action = "CreateNewWindow" },
  # { key = "o", mods = "Control | Shift", command = { program = "alacritty", args = [
  # "-e",
  # "wsl ~/code/scripts/{somescript}.sh",
  # ] } },
  { key = "v", mods = "Control", action = "Paste" },
  { key = "Enter", mods = "Alt", action = "ToggleFullscreen" },
]

[colors.primary]
# background = "#000000"
# background = "#0c0c15"
background = "#07070a"
