# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false


# Which is equivalent to
format = """
$character\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs"""

[character]
success_symbol = '[▲](bold green)'
# success_symbol = '[➜](bold green)'
